version: 2
endpoint: http://localhost:8080
admin_secret: myadminsecretkey
metadata_directory: metadata
migrations_directory: migrations
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000/api
